# Generated by Django 4.1.2 on 2022-12-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0012_delete_uploadedfile2_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataikan", name="tahun", field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
