# Generated by Django 4.1.2 on 2022-12-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0013_alter_dataikan_tahun_alter_uploadedfile_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(model_name="dataikan", name="tahun",),
    ]
