# Generated by Django 4.1.2 on 2022-12-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0014_remove_dataikan_tahun"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataikan", name="tahun", field=models.FloatField(null=True),
        ),
    ]
