# Generated by Django 4.1.2 on 2023-01-07 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0016_uploadedfilejson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfilejson", old_name="name", new_name="name_krolofil",
        ),
        migrations.RemoveField(model_name="uploadedfilejson", name="file",),
        migrations.AddField(
            model_name="uploadedfilejson",
            name="file_krolofil",
            field=models.FileField(
                null=True,
                upload_to="static/json/krolofil/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["json"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="uploadedfilejson",
            name="file_suhu",
            field=models.FileField(
                null=True,
                upload_to="static/json/suhu/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["json"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="uploadedfilejson",
            name="name_suhu",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
