# Generated by Django 4.1.2 on 2023-01-07 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0017_rename_name_uploadedfilejson_name_krolofil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfilejson",
            name="file_krolofil",
            field=models.FileField(
                null=True,
                upload_to="static/json/krolofil/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["js"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfilejson",
            name="file_suhu",
            field=models.FileField(
                null=True,
                upload_to="static/json/suhu/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["js"]
                    )
                ],
            ),
        ),
    ]
