# Generated by Django 4.1.2 on 2023-01-07 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0018_alter_uploadedfilejson_file_krolofil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFileLegenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_suhu", models.CharField(max_length=100, null=True)),
                ("name_krolofil", models.CharField(max_length=100, null=True)),
                (
                    "file_suhu",
                    models.FileField(
                        null=True,
                        upload_to="static/legenda/suhu",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "file_krolofil",
                    models.FileField(
                        null=True,
                        upload_to="static/legenda/krolofil",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
