# Generated by Django 4.1.2 on 2023-01-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MSY", "0019_uploadedfilelegenda"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadedFile",),
    ]
